In [26]:
#Index retrieval
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x)

(array([1, 4]),)


In [27]:
#
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,3,side='left')
print(x)

4


In [28]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))
a=np.array([[7,4,9],[9,1,4]])
print(np.sort(a))

[2 4 5 6 7 9]
[[4 7 9]
 [1 4 9]]


In [29]:
#Boolean Indexing
arr=np.array([31,78,69,88])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[78 88]


In [30]:
arr=np.array([31,78,69,88])
filter_arr=arr<70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False  True False]
[31 69]
