In [ ]:
#slice with step of one
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [ ]:
#slice with step of two
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [ ]:
#reverse slicing
slice3=arr[::-1]
print(slice3)

[9 8 7 6 5 4 3 2 1]


In [ ]:
#reverse slicing2
slice4=arr[::-2]
print(slice4)

[9 7 5 3 1]


In [ ]:
#slicing twodimenstional array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
#slice array 0 to 2 column 1 to 3
slice5=arr2[0:2,1:3]
print(slice5)

[[2 3]
 [5 6]]


In [ ]:
#extracting first column
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
c01=arr3[:,0]
print(c01)

[1 4 7]


In [ ]:
#extracting second row
r02=arr3[1,:]
print(r02)

[4 5 6]


In [ ]:
#extraction3
print(arr3[0,0])
print(arr3[1,2])

1
6


In [ ]:
#basic indexing
arr=np.array([10,20,30,40,50])
print(arr[1])


20


In [ ]:
#subset indexing
print(arr[1:4])

[20 30 40]


In [ ]:
print(arr[arr>25])

[30 40 50]


In [ ]:
#horizontal joint
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#vertical joint
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result2=np.vstack((arr1,arr2))
print(result2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#depth joint
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result3=np.dstack((arr1,arr2))
print(result3)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
#splitting in numpy
arr=np.array([1,2,3,4,5,6])
result4=np.split(arr,2)
print(result4)



[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
arr=np.array([1,2,3,4,5,6])
result5=np.split(arr,3)
print(result5)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#splitting unequal parts
result=np.array_split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#horizontal splitting
arr=np.array([[1,2],[3,4],[5,6]])
result6=np.hsplit(arr,2)
print(result6)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [ ]:
#vertical splitting
result7=np.vsplit(arr,3)
print(result7)


[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
