In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print("Datatype of an array:",arr.dtype)

Datatype of an array: int32


In [5]:
print("Shape of an array:",arr.shape)

Shape of an array: (9,)


In [6]:
print("Size of an array:",arr.size)


Size of an array: 9


In [8]:
print("Reverse of an array;",arr[::-1])

Reverse of an array; [9 8 7 6 5 4 3 2 1]


In [10]:
print("Data greater than 7:",arr[arr>7])

Data greater than 7: [8 9]


In [12]:
print("slicing of an array:",arr[0:8:2])

slicing of an array: [1 3 5 7]


In [13]:
print("Length of an array:",len(arr))

Length of an array: 9


In [15]:
import numpy as np
brr=np.array([[3,1,7],[4,2,9],[10,6,2],[11,2,5]])

In [17]:
print("Original array:\n",brr)
print("Reshaped the array:\n",brr.reshape(3,4))

Original array:
 [[ 3  1  7]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]
Reshaped the array:
 [[ 3  1  7  4]
 [ 2  9 10  6]
 [ 2 11  2  5]]


In [19]:
print("Sorted array:\n",np.sort(brr))

Sorted array:
 [[ 1  3  7]
 [ 2  4  9]
 [ 2  6 10]
 [ 2  5 11]]


In [20]:
print("Original Array:\n",brr)
print("Slicing Multidimensional array:\n",brr[0:3,1:3])

Original Array:
 [[ 3  1  7]
 [ 4  2  9]
 [10  6  2]
 [11  2  5]]
Slicing Multidimensional array:
 [[1 7]
 [2 9]
 [6 2]]


In [21]:
print("Extract the row1:\n",brr[0,:])

Extract the row1:
 [3 1 7]


In [22]:
print("Extract the column 1:",brr[:,0])

Extract the column 1: [ 3  4 10 11]
