In [45]:
import numpy as np
a=np.array([10,20,30])
print("One dimensional array:",a)


One dimensional array: [10 20 30]


In [46]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print("Two dimensional array:",b)

Two dimensional array: [[1 2 3]
 [4 5 6]]


In [47]:
import numpy as np
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Three dimensional array:",c)

Three dimensional array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
import numpy as np
d=np.zeros((3,5))
print("\n array with all zereos\n",d)


 array with all zereos
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
import numpy as np
e=np.random.random((3,2))
print("\nrandom value:\n",e)


random value:
 [[0.42703665 0.87403206]
 [0.58728088 0.80507774]
 [0.84669018 0.97148187]]


In [50]:
import numpy as np
f=np.arange(10,30,5)
print("\n sequence array :\n",f)



 sequence array :
 [10 15 20 25]


In [51]:
import numpy as np
a=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
b=a.reshape(4,3)
print("\n old array :\n",a)
print("\n reshaped array:\n",b)


 old array :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 reshaped array:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [52]:
import numpy as np
a=np.zeros((5,3))
b=np.random.random((5,3))
c=np.arange(0,10,2)
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
e=arr.reshape(6,2)
print("Array with zeros:",a)
print("\n Array with random values:\n",b)
print("\n Array in step:\n",c)
print("\n Old array: \n",arr)
print("\n Reshaped array:\n",e)

Array with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random values:
 [[0.36642561 0.38738942 0.87582925]
 [0.78252141 0.11858509 0.66486702]
 [0.34179244 0.94676971 0.44838936]
 [0.26974944 0.02184409 0.18951593]
 [0.87831494 0.04269683 0.04217289]]

 Array in step:
 [0 2 4 6 8]

 Old array: 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array:
 [[1 2]
 [3 4]
 [5 2]
 [4 2]
 [1 2]
 [0 1]]


In [53]:
#flatten array
import numpy as np
flat=arr.flatten()
print("Flattened array:\n",flat)

Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [54]:
#print type of element
print("\n Array element type",arr.dtype)


 Array element type int64


In [55]:
#convert integer to float
newtype = arr.astype('f')
print("\n convert array element: \n",newtype)
print("converted array:",newtype.dtype)


 convert array element: 
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
converted array: float32


In [56]:
#Determine the size of the array
size=len(arr)
print("\n size of array:\n",size)



 size of array:
 3
